```{r}
library(tidyverse)
library(ggrepel)
library(MASS)
```

```{r}
books <- read.table("books.dat", header=T, row.names="author")
summary(books)
```

```{r}
apply(books, 2, var)
```

Above graph does not contain obvious pattern
  -> instead, use proportion of the total page for each book

```{r, fig.height=10, fig.width=10}
portion.func <- function(df){
  row.sums <- rowSums(df)
  portion.df <- df / row.sums
  return(portion.df)
}
portion.books <- portion.func(books)
portion.sc.books <- scale(portion.books)
portion.sc.books.dist <- dist(portion.sc.books)
portion.sc.books.mds <- cmdscale(portion.sc.books.dist)
rownames(portion.sc.books.mds) <- row.names(portion.sc.books)
df.portion.sc.books.mds <- data.frame(portion.sc.books.mds)

ggplot(df.portion.sc.books.mds, aes(X1, X2)) +
  geom_point() +
  geom_text_repel(aes(label = rownames(df.portion.sc.books.mds))) +
  labs(title = "Classical MDS Solution using Euclidean Distance",
    subtitle = "proportion, scaled",
    x = "Dimension 1",
    y = "Dimension 2") +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  theme(panel.background = element_rect(fill = "white",
                                        colour = "grey90"))

portion.sc.books.mds.result <- cmdscale(portion.sc.books.dist, eig = TRUE)
print(portion.sc.books.mds.result$GOF)
```
```{r, fig.height=10, fig.width=10}
portion.other.mds <- isoMDS(portion.sc.books.dist)
df.portion.other.mds <- data.frame(portion.other.mds)

ggplot(df.portion.other.mds, aes(points.1, points.2)) +
  geom_point() +
  geom_text_repel(aes(label = rownames(df.portion.other.mds))) +
  labs(title = "Method 1 using isoMDS",
    x = "Dimension 1",
    y = "Dimension 2") +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  theme(panel.background = element_rect(fill = "white",
                                        colour = "grey90"))
```

```{r, fig.height=10, fig.width=10}
books.t <- t(books)
books.cor <- cor(books.t)
books.diss <- sqrt(2*(1 - books.cor))
books.diss.mds <- cmdscale(books.diss)
rownames(books.diss.mds) <- row.names(books.diss)
df.books.diss.mds <- data.frame(books.diss.mds)

ggplot(df.books.diss.mds, aes(X1, X2)) +
  geom_point() +
  geom_text_repel(aes(label = rownames(df.books.diss.mds))) +
  labs(title = "Classical MDS Solution using Correlation Coefficients",
    subtitle = "original, non-scaled",
    x = "Dimension 1",
    y = "Dimension 2") +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  theme(panel.background = element_rect(fill = "white",
                                        colour = "grey90"))

books.cor.mds.result <- cmdscale(books.cor, eig = TRUE)
print(books.cor.mds.result$GOF)
```
```{r, fig.height=10, fig.width=10}
books.diss.other.mds <- isoMDS(books.diss)
df.books.diss.other.mds <- data.frame(books.diss.other.mds)

ggplot(df.books.diss.other.mds, aes(points.1, points.2)) +
  geom_point() +
  geom_text_repel(aes(label = rownames(df.books.diss.other.mds))) +
  labs(title = "Method 2 using isoMDS",
    x = "Dimension 1",
    y = "Dimension 2") +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  theme(panel.background = element_rect(fill = "white",
                                        colour = "grey90"))
```